// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJz736z-bm1Gg5uxFPMNJQ01OkroZWBvo',
    appId: '1:719326293072:web:99cc06ab4dad526f603555',
    messagingSenderId: '719326293072',
    projectId: 'shoeshop-87640',
    authDomain: 'shoeshop-87640.firebaseapp.com',
    storageBucket: 'shoeshop-87640.appspot.com',
    measurementId: 'G-SND807S5J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-37E-0gDIwEMrdKjsbknMVdd-y7dIjuQ',
    appId: '1:719326293072:android:7387e87503f7d3d9603555',
    messagingSenderId: '719326293072',
    projectId: 'shoeshop-87640',
    storageBucket: 'shoeshop-87640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOv2S6Dbq7jVk2oyJ9ROmImwf8xM9O2R0',
    appId: '1:719326293072:ios:73f12f8ea11fae68603555',
    messagingSenderId: '719326293072',
    projectId: 'shoeshop-87640',
    storageBucket: 'shoeshop-87640.appspot.com',
    androidClientId: '719326293072-94b9ruc8463jt5ask057vqm0rbddh2kh.apps.googleusercontent.com',
    iosClientId: '719326293072-sr1h5t5h367lgaid8tujgq68r7vk9um0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesShop',
  );
}
